server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/NewGr8Player/Springcloud-demo/
          searchPaths: service-helloworld/src/main/resources/
          username:
          password:
